# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Botao1 = QtWidgets.QPushButton(self.centralwidget)
        self.Botao1.setGeometry(QtCore.QRect(490, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Botao1.setFont(font)
        self.Botao1.setAutoFillBackground(False)
        self.Botao1.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.Botao1.setIconSize(QtCore.QSize(20, 20))
        self.Botao1.setObjectName("Botao1")
        self.Botao2 = QtWidgets.QPushButton(self.centralwidget)
        self.Botao2.setGeometry(QtCore.QRect(180, 420, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Botao2.setFont(font)
        self.Botao2.setAutoFillBackground(False)
        self.Botao2.setStyleSheet("background-color: rgb(255, 241, 188);")
        self.Botao2.setIconSize(QtCore.QSize(20, 20))
        self.Botao2.setObjectName("Botao2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 170, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Botao1.setText(_translate("MainWindow", "Botão 1"))
        self.Botao2.setText(_translate("MainWindow", "Botão 2"))
        self.label.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
